# Generated by Django 3.0.14 on 2022-09-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=255)),
                ('Genero', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
