# Generated by Django 3.0.14 on 2022-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20220922_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='librosBd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=255)),
                ('Genero', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('FechaCompra', models.DateField(blank=True, null=True)),
                ('estadoLectura', models.CharField(max_length=255, null=True)),
                ('numeroPaginas', models.IntegerField(blank=True, null=True)),
                ('numeroLeidas', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
